
<br/>
<br/>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/ministros/secretaria-general-de-la-presidencia/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/Eyzaguirre.jpg" class="attachment-post-thumbnail wp-post-image" alt="Eyzaguirre"></a>
	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/ministros/secretaria-general-de-la-presidencia/">Nicolás Eyzaguirre Guzmán</a></h4>
		<h5 class="cargo">Ministro Secretario General de la Presidencia</h5>
		<h5 class="institucion">Ministerio Secretaría General de la Presidencia</h5>
		<i>Presidente del Comité de Ministros de Desarrollo Digital</i>
		<div class="links first">
			<a class="biografia" href="http://www.gob.cl/ministros/secretaria-general-de-la-presidencia/">Ver biografía completa</a>
			<a class="sitio" href="http://www.minsegpres.gob.cl/">Ir al sitio web</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/ministros/interior/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/Burgos.jpg" class="attachment-post-thumbnail wp-post-image" alt="Burgos"></a>

	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/ministros/interior/">Jorge Burgos Varela</a></h4>

		<h5 class="cargo">Ministro del Interior y Seguridad Pública</h5>
		<h5 class="institucion">Ministerio del Interior y Seguridad Pública</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/ministros/interior/">Ver biografía completa</a>
			<a class="sitio" href="http://interior.gob.cl/">Ir al sitio web</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/ministros/hacienda/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/IMG_7600_gob.jpg" class="attachment-post-thumbnail wp-post-image" alt="IMG_7600_gob"></a>

	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/ministros/hacienda/">Rodrigo Valdés Pulido</a></h4>

		<h5 class="cargo">Ministro de Hacienda</h5>
		<h5 class="institucion">Ministerio de Hacienda</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/ministros/hacienda/">Ver biografía completa</a>
			<a class="sitio" href="http://www.hacienda.cl/">Ir al sitio web</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/ministros/economia-fomento-y-turismo/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/Cespedes.jpg" class="attachment-post-thumbnail wp-post-image" alt="Cespedes"></a>

	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/ministros/economia-fomento-y-turismo/">Luis Felipe Céspedes Cifuentes</a></h4>

		<h5 class="cargo">Ministro de Economía, Fomento y Turismo</h5>
		<h5 class="institucion">Ministerio de Economía, Fomento y Turismo</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/ministros/economia-fomento-y-turismo/">Ver biografía completa</a>
			<a class="sitio" href="http://www.economia.gob.cl/">Ir al sitio web</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/ministros/educacion/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/delpiano.png" class="attachment-post-thumbnail wp-post-image" alt="delpiano"></a>

	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/ministros/educacion/">Adriana Delpiano</a></h4>

		<h5 class="cargo">Ministra de Educación</h5>
		<h5 class="institucion">Ministerio de Educación</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/ministros/educacion/">Ver biografía completa</a>
			<a class="sitio" href="http://www.mineduc.cl/">Ir al sitio web</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/ministros/ministro-de-salud-s/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/Foto-Oficial-Ministra-de-Salud_GOB.CL-11.jpg" class="attachment-post-thumbnail wp-post-image" alt="Ministra de Salud"></a>

	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/ministros/ministro-de-salud-s/">Carmen Castillo Taucher</a></h4>

		<h5 class="cargo">Ministra de Salud</h5>
		<h5 class="institucion">Ministerio de Salud</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/ministros/ministro-de-salud-s/">Ver biografía completa</a>
			<a class="sitio" href="http://web.minsal.cl/">Ir al sitio web</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>		

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/ministros/ministro-de-transporte-y-telecomunicaciones/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/Gomez-Lobo.jpg" class="attachment-post-thumbnail wp-post-image" alt="Gomez-Lobo"></a>
		
	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/ministros/ministro-de-transporte-y-telecomunicaciones/">Andrés Gómez-Lobo</a></h4>
		
		<h5 class="cargo">Ministro de Transporte y Telecomunicaciones</h5>
		<h5 class="institucion">Ministerio de Transporte y Telecomunicaciones</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/ministros/ministro-de-transporte-y-telecomunicaciones/">Ver biografía completa</a>
			<a class="sitio" href="http://www.mtt.gob.cl/">Ir al sitio web</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>																