<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta charset="utf-8">

	<title><?php echo $page->get("headline|title"); ?></title>

    <meta property="og:site_name" content="Desarrollo digital Gobierno de Chile"> 
	<meta name="description" property="og:description" content="Portal de la política nacional de desarrollo digital destinada a impulsar iniciativas que promuevan la adopción y uso de las tecnologías de información y comunicación por parte de todos los actores de la sociedad cuyo objetivo es contribuir al desarrollo económico, político y social en Chile" />

    <meta name="author" content="Unidad de Modernización y Gobierno Digital, Ministerio Secretaría General de la Presidencia de la República de Chile" />
 
    <meta property="article:publisher" content="http://www.modernizacion.gob.cl" />

    <meta name="generator" content="ProcessWire <?php echo $config->version; ?>" />


    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="">

    <link rel="icon" href="../../favicon.ico">

	<link rel="stylesheet" type="text/css" href="<?php echo $config->urls->templates?>css/main.css" />

	<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="<?php echo $config->urls->templates?>css/ie.css" />
	<![endif]-->	

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $config->urls->templates?>css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo $config->urls->templates?>css/main.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="<?php echo $config->urls->templates?>js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
