
<br/>
<br/>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/subsecretarios/secretaria-general-de-la-presidencia/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/SUBSE_patricia-silva-melendez1.jpg" class="attachment-post-thumbnail wp-post-image" alt="Eyzaguirre"></a>
	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/subsecretarios/secretaria-general-de-la-presidencia/">Patricia Silva Meléndez</a></h4>
		<h5 class="cargo">Subsecretaria General de la Presidencia</h5>
		<h5 class="institucion">Ministerio Secretaría General de la Presidencia</h5>
		<i>Preside Secretaría Ejecutiva</i>
		<div class="links first">
			<a class="biografia" href="http://www.gob.cl/subsecretarios/secretaria-general-de-la-presidencia/">Ver biografía completa</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/ministros/interior/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/SUBSE_Alejandro-Micco1.jpg" class="attachment-post-thumbnail wp-post-image" alt="Burgos"></a>

	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/subsecretarios/hacienda/">Alejandro Micco Aguayo</a></h4>

		<h5 class="cargo">Subsecretario de Hacienda</h5>
		<h5 class="institucion">Ministerio de Hacienda</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/subsecretarios/hacienda/">Ver biografía completa</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/subsecretarios/economia-y-empresas-de-menor-tamano/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/SUBSE_Katia-Trusich1.jpg" class="attachment-post-thumbnail wp-post-image" alt="IMG_7600_gob"></a>
		
	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/subsecretarios/economia-y-empresas-de-menor-tamano/">Katia Trusich Ortiz</a></h4>
		
		<h5 class="cargo">Subsecretaria de Economía y Empresas de Menor Tamaño</h5>
		<h5 class="institucion">Ministerio de Economía, Fomento y Turismo</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/subsecretarios/economia-y-empresas-de-menor-tamano/">Ver biografía completa</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<div class="member-card">
	<div class="pic pull-left">
		<a target="_blank" href="http://www.gob.cl/subsecretarios/telecomunicaciones/"><img width="120" src="http://www.gob.cl/wp-content/uploads/2014/03/SUBSE_Pedro-Huichalaf1.jpg" class="attachment-post-thumbnail wp-post-image" alt="Cespedes"></a>
		
	</div>
	<div class="texto pull-left">
		<h4 class="title"><a target="_blank" href="http://www.gob.cl/subsecretarios/telecomunicaciones/">Pedro Huichalaf Roa</a></h4>
		
		<h5 class="cargo">Subsecretario de Telecomunicaciones</h5>
		<h5 class="institucion">Ministerio de Transporte y Telecomunicaciones</h5>
		<div class="links">
			<a class="biografia" href="http://www.gob.cl/subsecretarios/telecomunicaciones/">Ver biografía completa</a>
		</div>
	</div>
	<div class="clearfix"></div>
</div>